# cloudbuild.yaml — Build & Deploy a Cloud Run (GCP)

substitutions:
  # Ajusta estos valores si quieres
  _SERVICE_NAME: gee-backend
  _REGION: us-central1          # ej: southamerica-west1 (Santiago) o us-central1
  _AR_LOCATION: us              # us / europe / asia o una región (p.ej., southamerica-west1)
  _AR_REPO: containers          # nombre de tu repositorio en Artifact Registry
  _PORT: "8080"                 # puerto en el que escucha tu app dentro del contenedor

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build de la imagen Docker
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
      - .

  # 2) Push de la imagen a Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}

  # 3) Deploy a Cloud Run (plataforma totalmente administrada)
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=${_PORT}
      # Opcionales comunes:
      - --memory=512Mi
      - --cpu=1
      - --concurrency=80
      - --min-instances=0
      - --max-instances=3
      # - --set-env-vars=ENV=prod,DEBUG=false

images:
  - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}

timeout: "1200s"
