# cloudbuild.yaml — Build & Deploy a Cloud Run con Secret Manager

substitutions:
  _SERVICE_NAME: gee-backend
  _REGION: southamerica-west1
  _AR_LOCATION: southamerica-west1
  _AR_REPO: containers
  _PORT: "8000"                             # tu FastAPI suele escuchar en 8000
  _RUNTIME_SA: aqp-bus@${PROJECT_ID}.iam.gserviceaccount.com

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build","-t",
           "${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}",
           "."]

  - name: gcr.io/cloud-builders/docker
    args: ["push",
           "${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}"]

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=${_PORT}
      - --service-account=${_RUNTIME_SA}
      - --timeout=600
      # Opcionales comunes:
      - --memory=128Mi
      - --cpu=1
      - --concurrency=80
      - --min-instances=0
      - --max-instances=3
      # # Env normales (no sensibles):
      # - --set-env-vars=POSTGRES_USER=postgres,POSTGRES_DB=python_demo,CLIENT_IDS=abc123
      # # Secretos desde Secret Manager:
      # - --set-secrets=POSTGRES_PASSWORD=projects/$PROJECT_ID/secrets/POSTGRES_PASSWORD:latest,JWT_SECRET_KEY=projects/$PROJECT_ID/secrets/JWT_SECRET_KEY:latest,DATABASE_URL=projects/$PROJECT_ID/secrets/DATABASE_URL:latest

images:
  - ${_AR_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY